
const KEY='gymTrackerV2';
const uid=()=>Math.random().toString(36).slice(2,9);
const makeEx=(name,sets=3,min=8,max=12,inc=2.5)=>({id:uid(),name,sets,min,max,inc,notes:''});
const defaults={settings:{restSeconds:120,currentDay:0},days:[
{name:'Day 1 - Push',id:uid(),exercises:[makeEx('Machine Chest Press'),makeEx('Incline Chest Press'),makeEx('Shoulder Press'),makeEx('Pec Deck',3,10,15),makeEx('Tricep Pushdown',3,10,15)]},
{name:'Day 2 - Pull',id:uid(),exercises:[makeEx('Lat Pulldown'),makeEx('Seated Cable Row'),makeEx('Chest Supported Row'),makeEx('Face Pull',3,12,15),makeEx('Incline Dumbbell Curl'),makeEx('Hammer Curl')]},
{name:'Day 3 - Legs',id:uid(),exercises:[makeEx('Leg Press',3,8,12,5),makeEx('Romanian Deadlift',3,6,10),makeEx('Leg Extension',3,10,15),makeEx('Seated Leg Curl',3,10,15)]},
{name:'Day 4 - Mixed',id:uid(),exercises:[makeEx('Deadlift',3,5,8),makeEx('Chest Press'),makeEx('Cable Row'),makeEx('Calf Raise',3,10,15)]}
],sessions:[],active:null};
let data=load(), timer=null, chartPts=[], graphMetric='weight', graphRange=12;
function load(){try{return JSON.parse(localStorage.getItem(KEY))||structuredClone(defaults)}catch{return structuredClone(defaults)}}
function save(){localStorage.setItem(KEY,JSON.stringify(data))}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function show(id){document.querySelectorAll('.page').forEach(p=>p.classList.toggle('active',p.id===id));document.querySelectorAll('.bottom-nav button').forEach(b=>b.classList.toggle('active',b.dataset.page===id));if(id==='workoutPage')renderWorkout();if(id==='historyPage'){}if(id==='libraryPage')renderLibrary();if(id==='settingsPage')renderSettings()}
document.querySelectorAll('.bottom-nav button').forEach(b=>b.onclick=()=>show(b.dataset.page));
document.getElementById('headerSettings').onclick=()=>show('settingsPage');

function day(){return data.days[data.settings.currentDay]||data.days[0]}
function histories(id){let out=[];data.sessions.forEach(s=>s.exercises.forEach(e=>{if(e.exerciseId===id)out.push({...e,date:s.date,day:s.day})}));return out.sort((a,b)=>b.date-a.date)}
function suggestion(ex){const h=histories(ex.id);if(!h.length)return{weight:0,text:'Start comfortably',action:''};const l=h[0],rs=l.reps.map(Number);if(rs.every(r=>r>=ex.max))return{weight:l.weight+ex.inc,text:`${l.weight+ex.inc} kg`,action:'Increase'};return{weight:l.weight,text:`${l.weight} kg`,action:'Stay'}}
function renderWorkout(){const d=day();document.getElementById('currentDayTitle').textContent=d.name.toUpperCase();const list=document.getElementById('exerciseList');list.innerHTML='';d.exercises.forEach((e,i)=>{const h=histories(e.id)[0],r=document.createElement('div');r.className='exercise-item';r.innerHTML=`<div class="exercise-index">${i+1}</div><div><strong>${esc(e.name)}</strong><small>${e.sets} sets · ${e.min} - ${e.max} reps</small></div><div class="exercise-stats"><strong>${h?h.weight+' kg':'—'}</strong><small>${h?h.reps.join(' / '):'No history'}</small></div><b>›</b>`;r.onclick=()=>openExercise(i);list.appendChild(r)})}
document.getElementById('changeDayBtn').onclick=()=>{data.settings.currentDay=(data.settings.currentDay+1)%data.days.length;save();renderWorkout()};
document.getElementById('addExerciseBtn').onclick=()=>show('libraryPage');

function openExercise(i){const d=day();if(!data.active||data.active.dayId!==d.id)data.active={dayId:d.id,day:d.name,index:i,started:Date.now(),entries:{},timerEnd:null,timerRemain:data.settings.restSeconds};data.active.index=i;save();renderExercise();show('exercisePage')}
function renderExercise(){const d=day(),i=data.active.index,e=d.exercises[i],hist=histories(e.id),last=hist[0],s=suggestion(e);document.getElementById('exerciseDayName').textContent=d.name;document.getElementById('exerciseCounter').textContent=`${i+1} of ${d.exercises.length}`;document.getElementById('activeExerciseName').textContent=e.name;document.getElementById('lastDate').textContent=last?fmt(last.date):'';document.getElementById('lastWeight').textContent=last?`${last.weight} kg`:'No data';document.getElementById('lastReps').textContent=last?last.reps.join(' / '):'—';document.getElementById('recommendWeight').textContent=s.text;document.getElementById('recommendAction').textContent=s.action;document.getElementById('recommendTarget').textContent=`Target: ${e.min}–${e.max} reps`;let entry=data.active.entries[e.id]||{weight:s.weight||0,reps:Array(e.sets).fill('')};data.active.entries[e.id]=entry;document.getElementById('currentWeight').textContent=`${entry.weight} kg`;document.getElementById('incrementText').textContent=`Increase by: ${e.inc} kg`;const sel=document.getElementById('setCountSelect');sel.innerHTML='';for(let n=1;n<=8;n++){const o=document.createElement('option');o.value=n;o.textContent=n;o.selected=n===entry.reps.length;sel.appendChild(o)};const rows=document.getElementById('setRows');rows.innerHTML='';entry.reps.forEach((r,j)=>{const row=document.createElement('div');row.className='set-row';row.innerHTML=`<span>Set ${j+1}</span><input type="number" inputmode="numeric" value="${r}" placeholder="0"><small>reps</small>`;row.querySelector('input').oninput=x=>{entry.reps[j]=x.target.value;save()};rows.appendChild(row)});document.getElementById('timerSecondsLabel').textContent=data.settings.restSeconds;updateTimer()}
document.getElementById('setCountSelect').onchange=e=>{const ex=day().exercises[data.active.index],entry=data.active.entries[ex.id],n=+e.target.value;while(entry.reps.length<n)entry.reps.push('');entry.reps=entry.reps.slice(0,n);save();renderExercise()};
document.getElementById('decWeight').onclick=()=>changeWeight(-1);document.getElementById('incWeight').onclick=()=>changeWeight(1);
function changeWeight(dir){const ex=day().exercises[data.active.index],entry=data.active.entries[ex.id];entry.weight=Math.max(0,+entry.weight+dir*ex.inc);save();renderExercise()}
document.getElementById('exerciseBack').onclick=()=>show('workoutPage');document.getElementById('prevExercise').onclick=()=>{if(data.active.index>0){data.active.index--;save();renderExercise()}};
document.getElementById('skipExercise').onclick=()=>nextExercise(false);document.getElementById('completeExercise').onclick=()=>nextExercise(true);
function nextExercise(saveIt){const d=day(),ex=d.exercises[data.active.index],entry=data.active.entries[ex.id];if(saveIt&&entry.reps.every(x=>x===''))return alert('Enter at least one set.');if(data.active.index<d.exercises.length-1){data.active.index++;save();renderExercise()}else finishSession()}
function finishSession(){const d=day(),arr=[];Object.entries(data.active.entries).forEach(([id,en])=>{const ex=d.exercises.find(x=>x.id===id);if(ex&&en.reps.some(x=>x!==''))arr.push({exerciseId:id,name:ex.name,weight:+en.weight,reps:en.reps.filter(x=>x!=='').map(Number)})});if(arr.length)data.sessions.unshift({id:uid(),date:Date.now(),day:d.name,started:data.active.started,exercises:arr});data.active=null;save();show('workoutPage')}

function timerState(){if(!data.active)return data.settings.restSeconds;if(data.active.timerEnd)return Math.max(0,Math.ceil((data.active.timerEnd-Date.now())/1000));return data.active.timerRemain??data.settings.restSeconds}
function updateTimer(){const r=timerState();document.getElementById('timerDisplay').textContent=`${String(Math.floor(r/60)).padStart(2,'0')}:${String(r%60).padStart(2,'0')}`}
document.getElementById('startTimerBtn').onclick=()=>{if(!data.active)return;data.active.timerEnd=Date.now()+timerState()*1000;save();clearInterval(timer);timer=setInterval(()=>{if(timerState()<=0){pauseTimer();data.active.timerRemain=0;save()}updateTimer()},250)}
function pauseTimer(){if(!data.active)return;data.active.timerRemain=timerState();data.active.timerEnd=null;clearInterval(timer);save();updateTimer()}
document.getElementById('pauseTimerBtn').onclick=pauseTimer;document.getElementById('resetTimerBtn').onclick=()=>{if(!data.active)return;clearInterval(timer);data.active.timerEnd=null;data.active.timerRemain=data.settings.restSeconds;save();updateTimer()}

function allExercises(){const m=new Map();data.days.forEach(d=>d.exercises.forEach(e=>m.set(e.id,e)));return [...m.values()]}
function renderLibrary(){const list=document.getElementById('libraryList'),q=(document.getElementById('exerciseSearch').value||'').toLowerCase();list.innerHTML='';allExercises().filter(e=>e.name.toLowerCase().includes(q)).forEach(e=>{const r=document.createElement('div');r.className='library-row';r.innerHTML=`<span>${esc(e.name)}</span><button>＋</button>`;r.querySelector('button').onclick=()=>{if(!day().exercises.some(x=>x.id===e.id))day().exercises.push(structuredClone(e));save();show('workoutPage')};list.appendChild(r)})}
document.getElementById('exerciseSearch').oninput=renderLibrary;document.getElementById('libraryClose').onclick=()=>show('workoutPage');document.getElementById('createExerciseBtn').onclick=()=>{const name=prompt('Exercise name');if(!name)return;const e=makeEx(name);day().exercises.push(e);save();show('workoutPage')};

document.querySelectorAll('[data-history]').forEach(b=>b.onclick=()=>openHistory(b.dataset.history));
document.getElementById('historyBack').onclick=()=>show('historyPage');document.getElementById('graphBack').onclick=()=>show('historyPage');
function openHistory(type){if(type==='graphs'){renderGraphPage();show('graphPage');return}const c=document.getElementById('historyDetailContent'),t=document.getElementById('historyDetailTitle');if(type==='past'){t.textContent='Past Sets & Reps';c.innerHTML=tablePast()}if(type==='weights'){t.textContent='Past Weights';c.innerHTML=tableWeights()}if(type==='max'){t.textContent='Max Weight Sets';c.innerHTML=tableMax()}if(type==='raw'){t.textContent='Raw Data';c.innerHTML=tableRaw()}show('historyDetailPage')}
function tablePast(){const rows=[];data.sessions.forEach(s=>s.exercises.forEach(e=>rows.push(`<tr><td>${fmt(s.date)}</td><td>${esc(e.name)}</td><td>${e.weight} kg</td><td>${e.reps[0]??''}</td><td>${e.reps[1]??''}</td><td>${e.reps[2]??''}</td></tr>`)));return wrapTable('<th>Date</th><th>Exercise</th><th>Weight</th><th>Set 1</th><th>Set 2</th><th>Set 3</th>',rows)}
function tableWeights(){const rows=[];data.sessions.forEach(s=>s.exercises.forEach(e=>rows.push(`<tr><td>${fmt(s.date)}</td><td>${esc(e.name)}</td><td>${e.weight} kg</td><td>${e.reps.join(' / ')}</td></tr>`)));return wrapTable('<th>Date</th><th>Exercise</th><th>Weight</th><th>Reps</th>',rows)}
function tableMax(){const rows=allExercises().map(e=>{let best=null;histories(e.id).forEach(h=>h.reps.forEach(r=>{if(!best||h.weight>best.weight||(h.weight===best.weight&&r>best.reps))best={weight:h.weight,reps:r,date:h.date}}));return best?`<tr><td>${esc(e.name)}</td><td>${best.weight} kg</td><td>${best.reps}</td><td>${fmt(best.date)}</td></tr>`:''}).filter(Boolean);return wrapTable('<th>Exercise</th><th>Max Weight</th><th>Reps</th><th>Date</th>',rows)}
function raw(){const rows=[];data.sessions.forEach(s=>s.exercises.forEach(e=>e.reps.forEach((r,i)=>rows.push({date:s.date,day:s.day,exercise:e.name,set:i+1,weight:e.weight,reps:r}))));return rows}
function tableRaw(){return wrapTable('<th>Date</th><th>Day</th><th>Exercise</th><th>Set</th><th>Weight</th><th>Reps</th>',raw().map(r=>`<tr><td>${fmt(r.date)}</td><td>${esc(r.day)}</td><td>${esc(r.exercise)}</td><td>${r.set}</td><td>${r.weight}</td><td>${r.reps}</td></tr>`))}
function wrapTable(h,rows){return `<div class="data-table-wrap"><table class="data-table"><thead><tr>${h}</tr></thead><tbody>${rows.join('')||'<tr><td colspan="7">No data yet</td></tr>'}</tbody></table></div>`}
document.getElementById('exportCsv').onclick=()=>{const csv=['Date,Day,Exercise,Set,Weight,Reps',...raw().map(r=>[new Date(r.date).toISOString(),r.day,r.exercise,r.set,r.weight,r.reps].map(x=>`"${String(x).replaceAll('"','""')}"`).join(','))].join('\n');download(csv,'gym-data.csv','text/csv')}

function renderGraphPage(){const s=document.getElementById('graphExercise'),cur=s.value;s.innerHTML='';allExercises().forEach(e=>{const o=document.createElement('option');o.value=e.id;o.textContent=e.name;s.appendChild(o)});if(cur)s.value=cur;drawChart()}
document.getElementById('graphExercise').onchange=drawChart;document.querySelectorAll('[data-metric]').forEach(b=>b.onclick=()=>{graphMetric=b.dataset.metric;document.querySelectorAll('[data-metric]').forEach(x=>x.classList.toggle('active',x===b));drawChart()});document.querySelectorAll('[data-range]').forEach(b=>b.onclick=()=>{graphRange=+b.dataset.range;document.querySelectorAll('[data-range]').forEach(x=>x.classList.toggle('active',x===b));drawChart()});
function drawChart(){const can=document.getElementById('chart'),ctx=can.getContext('2d'),id=document.getElementById('graphExercise').value;let h=histories(id).reverse();if(graphRange){const cut=Date.now()-graphRange*30.4*864e5;h=h.filter(x=>x.date>=cut)}let pts=h.map(x=>({date:x.date,label:shortFmt(x.date),value:graphMetric==='weight'?x.weight:graphMetric==='reps'?x.reps.reduce((a,b)=>a+b,0):graphMetric==='volume'?x.reps.reduce((a,b)=>a+b,0)*x.weight:Math.max(...x.reps)}));ctx.clearRect(0,0,can.width,can.height);ctx.fillStyle='#0d0f10';ctx.fillRect(0,0,can.width,can.height);chartPts=[];if(!pts.length){ctx.fillStyle='#8b8f93';ctx.font='28px system-ui';ctx.textAlign='center';ctx.fillText('No graph data yet',450,260);return}const pad={l:75,r:30,t:35,b:65},vals=pts.map(x=>x.value),lo=Math.max(0,Math.min(...vals)-2),hi=Math.max(...vals)+2;ctx.strokeStyle='#24272a';ctx.fillStyle='#8b8f93';ctx.font='18px system-ui';ctx.textAlign='right';for(let i=0;i<5;i++){const y=pad.t+(520-pad.t-pad.b)*i/4,v=hi-(hi-lo)*i/4;ctx.beginPath();ctx.moveTo(pad.l,y);ctx.lineTo(900-pad.r,y);ctx.stroke();ctx.fillText(v.toFixed(v%1?1:0),pad.l-10,y+6)}const xf=i=>pts.length===1?450:pad.l+(900-pad.l-pad.r)*i/(pts.length-1),yf=v=>pad.t+(hi-v)/(hi-lo||1)*(520-pad.t-pad.b);ctx.strokeStyle='#ff7a00';ctx.lineWidth=4;ctx.beginPath();pts.forEach((p,i)=>i?ctx.lineTo(xf(i),yf(p.value)):ctx.moveTo(xf(i),yf(p.value)));ctx.stroke();pts.forEach((p,i)=>{const x=xf(i),y=yf(p.value);chartPts.push({x,y,p});ctx.fillStyle='#ff7a00';ctx.beginPath();ctx.arc(x,y,7,0,Math.PI*2);ctx.fill();ctx.fillStyle='#8b8f93';ctx.textAlign='center';ctx.fillText(p.label,x,485)})}
document.getElementById('chart').onclick=e=>{const r=e.currentTarget.getBoundingClientRect(),x=(e.clientX-r.left)*900/r.width,y=(e.clientY-r.top)*520/r.height,b=chartPts.map(p=>({...p,d:Math.hypot(p.x-x,p.y-y)})).sort((a,b)=>a.d-b.d)[0];if(!b||b.d>35)return;const tip=document.getElementById('chartTip');tip.textContent=`${fmt(b.p.date)} — ${b.p.value}`;tip.style.left=e.clientX+'px';tip.style.top=e.clientY+'px';tip.classList.remove('hidden')}

function renderSettings(){document.getElementById('restSecondsInput').value=data.settings.restSeconds}
document.getElementById('restSecondsInput').onchange=e=>{data.settings.restSeconds=Math.max(10,+e.target.value||120);save()}
document.getElementById('editDaysBtn').onclick=()=>{renderDays();show('daysPage')};document.getElementById('daysBack').onclick=()=>show('settingsPage');
function renderDays(){const el=document.getElementById('daysEditor');el.innerHTML='';data.days.forEach((d,i)=>{const x=document.createElement('div');x.className='day-editor';x.innerHTML=`<input value="${esc(d.name)}"><button class="small-btn">Delete</button>`;x.querySelector('input').oninput=e=>{d.name=e.target.value;save()};x.querySelector('button').onclick=()=>{if(data.days.length>1){data.days.splice(i,1);data.settings.currentDay=0;save();renderDays()}};el.appendChild(x)})}
document.getElementById('addDayBtn').onclick=()=>{data.days.push({id:uid(),name:`Day ${data.days.length+1}`,exercises:[]});save();renderDays()}
document.getElementById('backupBtn').onclick=()=>download(JSON.stringify(data,null,2),'gym-backup.json','application/json');
document.getElementById('restoreInput').onchange=async e=>{try{data=JSON.parse(await e.target.files[0].text());save();location.reload()}catch{alert('Could not restore backup')}}
function download(content,name,type){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([content],{type}));a.download=name;a.click()}
function fmt(ts){return new Intl.DateTimeFormat('en-GB',{day:'numeric',month:'short',year:'numeric'}).format(new Date(ts))}
function shortFmt(ts){return new Intl.DateTimeFormat('en-GB',{month:'short',year:'2-digit'}).format(new Date(ts))}
if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js');renderWorkout()
